--  double (double 2)
-- = { applying the inner double }
-- double (2 + 2)
-- = { applying double }
-- (2 + 2) + (2 + 2)
-- = { applying the first + }
-- 4 + (2 + 2)
-- = { applying the second + }
-- 4 + 4
-- = { applying + }
-- 8
