-- In hugs
-- Main> ['1', ['2', '3']]
-- ERROR - Type error in list
-- *** Expression     : ['1',['2','3']]
-- *** Term           : ['2','3']
-- *** Type           : [Char]
-- *** Does not match : Char
